config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :menus
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  mount ActionCable.server => '/cable'

  root 'welcome#index'

  get 'welcome/index'

  resources :reservations, only: %i[create show]
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu.rb
# frozen_string_literal: true

class Menu < ApplicationRecord
  has_many :reservation_menus

  def reserved_menus
    reservation_menus.reduce(0) do |a, b|
      a + (b&.count).to_i
    end
  end
end

app/models/reservation.rb
# frozen_string_literal: true

class Reservation < ApplicationRecord
  after_save :broadcast_creation

  belongs_to :table, optional: false
  has_many :reservation_menus, inverse_of: :reservation, dependent: :destroy
  has_many :menus, through: :reservation_menus

  accepts_nested_attributes_for :reservation_menus

  validates :firstname, presence: true
  validates :lastname, presence: true

  validate :full_table

  private

  def broadcast_creation
    ActionCable.server.broadcast 'reservations', reservation: self
  end

  def full_table
    errors.add(:table, :full) if !table.nil? && table.reserved_places + number > table.capacity
  end
end

app/models/reservation_menu.rb
# frozen_string_literal: true

class ReservationMenu < ApplicationRecord
  belongs_to :menu
  belongs_to :reservation, inverse_of: :reservation_menus
end

app/models/table.rb
# frozen_string_literal: true

class Table < ApplicationRecord
  has_many :reservations, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :capacity, presence: true

  def reserved_places
    reservations.sum(:number)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/reservations_controller.rb
# frozen_string_literal: true

class ReservationsController < ApplicationController
  before_action :set_reservation, only: %i[show edit update destroy]

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show; end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit; end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)

    @reservation.number = @reservation.reservation_menus.reduce(0) do |a, b|
      a + (b&.count).to_i
    end

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.js   {}
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.js   {}
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_reservation
    @reservation = Reservation.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def reservation_params
    params.require(:reservation).permit(
      :firstname,
      :lastname,
      :friends,
      :phone_number,
      :number,
      :table_id,
      :paiementMode,
      reservation_menus_attributes: %i[
        menu_id
        count
      ]
    )
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index
    @tables = Table.all
    @reservation = Reservation.new
    @menus = Menu.all.order(:id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/reservations_helper.rb
# frozen_string_literal: true

module ReservationsHelper
end

app/helpers/tables_helper.rb
# frozen_string_literal: true

module TablesHelper
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1, user-scalable=no", :name => "viewport"}/
    %title JDN2019
    = csrf_meta_tags
    = action_cable_meta_tag
    %link{rel: "stylesheet", href: "https://use.fontawesome.com/releases/v5.5.0/css/all.css", integrity: "sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU", crossorigin: "anonymous"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{rel: "stylesheet", href: "/main-assets/css/main.css"}
  %body.landing
    = yield

app/views/reservations/_form.html.haml
= form_for @reservation do |f|
  - if @reservation.errors.any?
    #error_explanation
      %h2= "#{pluralize(@reservation.errors.count, "error")} prohibited this reservation from being saved:"
      %ul
        - @reservation.errors.full_messages.each do |message|
          %li= message

  .actions
    = f.submit 'Save'

app/views/reservations/create.js.erb
<% if @reservation.errors.empty? %>
  alert('Votre réservation a bien été prise en compte')
<% else %>
  var errors = <%= @reservation.errors.full_messages.to_json.html_safe %>;
  alert("Il y a des erreurs dans votre formulaire: \n" + errors.map(function(error) { return "- "+error+"\n" }).join(''));
<% end %>

app/views/reservations/edit.html.haml
%h1 Editing reservation

= render 'form'

= link_to 'Show', @reservation
\|
= link_to 'Back', reservations_path

app/views/reservations/index.html.haml
%h1 Listing reservations

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @reservations.each do |reservation|
      %tr
        %td= link_to 'Show', reservation
        %td= link_to 'Edit', edit_reservation_path(reservation)
        %td= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Reservation', new_reservation_path

app/views/reservations/new.html.haml
%h1 New reservation

= render 'form'

= link_to 'Back', reservations_path

app/views/reservations/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_reservation_path(@reservation)
\|
= link_to 'Back', reservations_path

app/views/welcome/index.html.haml
%noscript
  %link{:href => "main-assets/css/noscript.css", :rel => "stylesheet"}/
/ Page Wrapper
#page-wrapper
  / Header
  %header#header.alt{:style => "background-color: #000000;"}
    %h1
      %a{:style => "color: #FFD700	;"} Just Diplomed Night 2019
  / Banner
  %section#banner
    .inner
      %h2{ :style => "color: #FFD700;"} Just Diplomed Night
      %p{ :style => "color: #FFD700;"}
        Le comité JDN 2019 est heureux de vous inviter pour une soirée d’exception sous le thème des oscars.
        %br/
        Le Samedi 16 Novembre 2019 à 19h30, au
        %a{href: 'https://www.google.com/maps/place/Hôtel+Mercure+Lille+Aéroport/@50.5838428,3.0907975,17z/data=!3m1!4b1!4m9!3m8!1s0x47c2d4275c36c0b1:0x16cb4a904f640e96!5m3!1s2018-10-14!4m1!1i2!8m2!3d50.5838428!4d3.0929862', target: '_blank'} Mercure Hotel de Lesquin.
      %ul.actions.special
        %li
          %a.button.primary{:href => "#new_reservation"} Réservez dès maintenant
    %a.more.scrolly{:href => "#one"} En savoir plus
  / One
  %section#one.wrapper.style1.special
    .inner
      %header.major
        %h2{ :style => "color: #FFD700;"}
          La JDN qu’est ce que c’est ?
        %p 
          La « Just Diplomed Night » est la soirée de gala de l’IG2I durant laquelle est diplômée la promotion sortante : la promotion 2019. Réunis autour d’un repas d’exception, les diplômés, leur famille, les anciens et actuels élèves de l’IG2I ainsi que le personnel de l’école se rassemblent pour partager un moment clôturant ces 5 années (et plus si affinité !). Toutes ces années ont été marquées par de nombreux souvenirs auxquels viendra s’ajouter celui de cette soirée qui s’annonce mémorable !
          
  %section#one.wrapper.style4.special
    .inner
      %header
        %h2{ :style => "color: #FFD700;"} Le Programme de la soirée
  %section#two.wrapper.alt.style1
    %section.spotlight
      .image
        %img{:alt => "", :src => "images/repasGastro.jpg"}/
      .content
        %h2{ :style => "color: #FFD700;"}
          Un repas gastronomique de qualité
        %p From pastabox to Chef ⭐⭐⭐
    %section.spotlight
      .image
        %img{:alt => "", :src => "images/film.jpg"}/
      .content
        %h2{ :style => "color: #FFD700;"}
          Des films dédiés à la promotion 2019
        %p Tourné en étroite collaboration avec les élèves, mais aussi avec le personnel administratif et enseignants.
    %section.spotlight
      .image
        %img{:alt => "", :src => "images/soiréedansante.jpeg"}/
      .content
        %h2{ :style => "color: #FFD700;"}
          Un groupe de musique et une soirée dansante 
        %p Pour danser jusqu'au bout de la nuit.
  / Three
  %section#one.wrapper.style4.special
    .inner
      %header
        %h2{ :style => "color: #FFD700;"} Le Menu
        %p{ :style => "color: #FFFFFF;"}
          Entrée : 
          </br>
          Saumon gravelax aux agrumes 
          %br
          %br
          Plat :
          %br
          Magret de canard, jus épicé
          %br
          %br
          Dessert : 
          %br
          Assortiments de mignardises du Chef Pâtisier Christophe CHALOPIN
          %br/ 
          %br/
          Boissons incluses dans le menu.

        %h2{ :style => "color: #FFD700;"} Les Tarifs
        %p
          %h2 Gala : 
          %b 30€
          pour les diplomés et cotisants BDE
          %br/ 
          %b 35€ 
          pour toutes autres personnes
          %h5 Réservation obligatoire pour participer au gala avant le 06 novembre 2019.
          %br/
          %h2 Hôtel :
          %p{ :style => "color: #FFFFFF;"} L'hôtel met à disposition des chambres à tarifs préférenciels.
          Chambre single + petit déjeuner pour 1 personne :  
          %b 75€. 
          %br/ 
          Chambre double + petit déjeuner pour 2 personnes : 
          %b 85€.
          %br/
          Chambre triple + petit déjeuner pour 3 personnes : 
          %b 95€.
          %br/
          Chambre quadruple + petit déjeuner pour 4 personnes : 
          %b 105€.
          %br/
          Sans petit-déjeuner les chambres sont à 75€ pour 1,2,3 et 4 personnes.
          %br/
          Taxe de séjour de 2€48 par personne. 
          %br/
          %h6 
            Adresse de réservation: 
            %br/
            %a{:href => 'mailto:H1098-RE@accor.com'} H1098-RE@accor.com 
            ou  03 20 87 46 46. Merci de bien préciser CENTRALE LILLE IG2I. 
  / Footer
  %footer#footer
    %h1{ :style => "color:red;font-size:24px;"} INSCRIPTIONS TERMINEES
    = form_for @reservation, remote: true do |form|
      .flex-row.flex-column-small
        .flex-column
          %h4
            Vos informations
          = form.text_field :firstname, placeholder: 'Prénom', :required => true, :disabled => true
          = form.text_field :lastname, placeholder: 'Nom', :required => true, :disabled => true
          = form.text_field :phone_number, placeholder: 'Numéro de téléphone', :required => true, :disabled => true
          = form.text_area :friends, placeholder: 'Nom des personnes accompagnantes si différent', :disabled => true
          %br/
          = form.label "Mode de paiement"
          = form.select :paiementMode, ["Sur place (liquide & chèque)","En ligne via lydia avant l'événement"], :disabled => true
          %i Pour les paiements avant l'événement nous vous enverrons une demande de paiement sur lydia via le numèro de téléphone utilisé lors de cette inscription.
        .flex-column
          %h4
            Votre réservation
          = form.collection_select(:table_id, @tables, :id, :name, prompt: 'Sélectionnez votre table (voir ci-dessous)')
          - @menus.each do |menu|
            = form.fields_for :reservation_menus, ReservationMenu.new do |rm|
              = rm.hidden_field :menu_id, value: menu.id
              %label.menu-label
                = "Nombre de menus \"#{menu.name}\""
              = rm.number_field :count, class: 'menu-input', :value => 0, :required => true, :min => 0, :max => 10
      .flex-row.flex-align-center.flex-justify-center
        = form.submit "S'inscrire"
    
    %a{ :download => "planTable.png", :href => "images/planTable.png", :target => "_blank" } plan de table
    #reservations
      - @tables.in_groups_of(4).each do |table_group|
        .flex-row.flex-column-small
          - table_group.each do |table|
            .flex-column.flex-column-small
              - unless table.nil?
                %table{:'data-table' => table.id}
                  %tr
                    %th
                      %b Table "#{table.name}"

                  - table.reservations.each do |reservation|
                    - reservation.number.times do
                      %tr
                        %td #{reservation.firstname} #{reservation.lastname}
                  - (table.capacity - table.reserved_places).times do
                    %tr
                      %td{:'data-empty' => true}
                        %i Place disponible

/ Scripts
= javascript_include_tag('/main-assets/js/jquery.min.js')
= javascript_include_tag('/main-assets/js/jquery.scrollex.min.js')
= javascript_include_tag('/main-assets/js/jquery.scrolly.min.js')
= javascript_include_tag('/main-assets/js/browser.min.js')
= javascript_include_tag('/main-assets/js/breakpoints.min.js')
= javascript_include_tag('/main-assets/js/util.js')
= javascript_include_tag('/main-assets/js/main.js')